export const FETCH_RESOURCES = 'FETCH_RESOURCES';
export const FETCH_COLLECTION_LIST = 'FETCH_COLLECTION_LIST';

export const SET_USER_INFO = 'SET_USER_INFO';
export const HIDE_ADMIN_MODAL = 'HIDE_ADMIN_MODAL';
export const SHOW_ADMIN_MODAL = 'SHOW_ADMIN_MODAL';

export const CREATE_TEAM = 'CREATE_TEAM';
export const UPDATE_TEAM = 'UPDATE_TEAM';
export const DELETE_TEAM = 'DELETE_TEAM';
export const GET_FULL_TEAM_LIST = 'GET_FULL_TEAM_LIST';
export const GET_TEAM_INFO = 'GET_TEAM_INFO';

export const CREATE_COLLECTION = 'CREATE_COLLECTION';
export const UPDATE_COLLECTION = 'UPDATE_COLLECTION';
export const DELETE_COLLECTION = 'DELETE_COLLECTION';
export const FETCH_COLLECTION = 'FETCH_COLLECTION';
export const FETCH_COLLECTIONS_BY_TEAM = 'FETCH_COLLECTIONS_BY_TEAM';
